# Generated by Django 3.2.12 on 2023-02-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(verbose_name='fecha_registro')),
                ('foto_perfil', models.ImageField(upload_to='f_perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha_creacion_hilo')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hilos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha_creacion_com')),
                ('contenido', models.TextField()),
                ('imagen_com_1', models.ImageField(upload_to='f_hilo')),
                ('imagen_com_2', models.ImageField(null=True, upload_to='f_hilo')),
                ('imagen_com_3', models.ImageField(null=True, upload_to='f_hilo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hilos.usuario')),
                ('nombre_hilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hilos.hilo')),
            ],
        ),
    ]
