# Generated by Django 3.2.12 on 2023-03-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=200)),
                ('apellido2', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('lugar', models.TextField(max_length=600)),
                ('integrante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parte_1', to='app_registro.persona')),
                ('integrante2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parte_2', to='app_registro.persona')),
            ],
        ),
    ]
